# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "durianpay-terraform-storage"
    encrypt = true
    key     = "./terraform.tfstate"
    region  = "ap-southeast-1"
  }
}
